language: node_js
sudo: false
cache:
  directories:
    - bower_components
    - node_modules
env:
  global:
    - GH_REF=github.com/amercier/todomvc-testing.git
    - secure: "dhWCWtsgluAaAueGeytyrAIfc4XpOeHEUuGr1r0+UHIhKocSXzLg0lq8u1blqJYBqK29cLzZOPFkZ+CDbhQlyDouK1DIk5tYvx52LhS4fGZxaCf0AxOFt4Hz6EWE5XeLGYG9+NfbOwb1xHJEvGERaWDq6Fja60ir2T0y28Vaa88="
  matrix:
    - TEST_SUITE=test
    - TEST_SUITE=lint-jshint
    - TEST_SUITE=lint-jsrc
    - TEST_SUITE=testem-test-vanillajs-jasmine
    - TEST_SUITE=testem-test-vanillajs-jasmine-blanket
    - TEST_SUITE=testem-test-vanillajs-mocha
    - TEST_SUITE=testem-test-vanillajs-mocha-blanket
    - TEST_SUITE=testem-test-vanillajs-qunit
    - TEST_SUITE=testem-test-vanillajs-qunit-blanket
    - TEST_SUITE=karma-test-vanillajs-jasmine
    - TEST_SUITE=karma-test-vanillajs-mocha
    - TEST_SUITE=karma-test-vanillajs-qunit
script: npm run $TEST_SUITE
after_success:
  - test $TEST_SUITE == test && mkdir dist
  - test $TEST_SUITE == test && echo ok > dist/index.html
  - test $TEST_SUITE == test && npm run-script deploy
