language: node_js
env:
  - TEST_SUITE=test-vanillajs-jasmine
  - TEST_SUITE=test-vanillajs-mocha
  - TEST_SUITE=test-vanillajs-qunit
node_js:
  - "0.11"
  - "0.10"
script: npm run $TEST_SUITE
sudo: false
