language: node_js
env:
  - TEST_SUITE=testem-test-vanillajs-jasmine
  - TEST_SUITE=testem-test-vanillajs-mocha
  - TEST_SUITE=testem-test-vanillajs-qunit
  - TEST_SUITE=karma-test-vanillajs-jasmine
  - TEST_SUITE=karma-test-vanillajs-mocha
node_js:
  - "0.11"
  - "0.10"
script: npm run $TEST_SUITE
sudo: false
